name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        perl: [ '5.34', '5.32', '5.24', '5.20', '5.18', '5.14', '5.12' ]
        include:
          - perl: '5.32'
            os: ubuntu-latest
            coverage: true
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm ExtUtils::PL2Bat
      - run: cpanm ExtUtils::MakeMaker
      - run: cpanm Async::Event::Interval
      - run: cpanm --installdeps .
      - name: Run tests (no coverage)
        env:
          CI_TESTING: 1
        if: ${{ !matrix.coverage }}
        run: prove -lv t
      - name: Run tests (with coverage)
        if: ${{ matrix.coverage }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_TESTING: 1
        run: |
          cpanm -n Devel::Cover::Report::Coveralls
          cover -test -report Coveralls
